archivesspace/tech-docs

- customization/plugins.md
Providing a link to Dallas's excellent Hello World README
> provide link to the "Hello world" plugin's README

- README_ORIGINAL.md
- architecture/ARCHITECTURE_original.md
I am doing spelling edits for git pull practice, cheers
Signed-off-by: zafar-hussain <zafar_hussain2000@hotmail.com>
> spelling edits for HACKTOBERFEST 2018

- administration/backup.md
- administration/getting_started.md
- customization/plugins.md
- development/docker.md
- development/reports.md
- provisioning/https.md
- provisioning/mysql.md
- provisioning/tuning.md
Also added new readme about adding reports
> Update readme files from archivesspace/archivesspace version 2.5.1

- customization/plugins.md
In order to add a report, it's necessary to add translations to the frontend (thanks @lorawoodford for cluing me in)
> Reports require translations.

- development/build.md
This page is hard to follow as is. I tried to clean it up a bit, and add in two important missing bits. One was the way to run everything at once using supervisord. The other was how to run the DB migrations when running things this way.  It's a bit longer, but I think it makes knowing how to do things more clear.
> Clarify some things about running from source

- development/public_test.md
Updates to `public_test.md` to reflect changes made in https://github.com/archivesspace/archivesspace/pull/1494
Note: This should NOT be merged until/unless the above PR is merged into core.  But, I didn't want to forget to do this!  ;-)
> Update public_test.md to reflect core code changes

- customization/theming.md
I think this was never updated for the 2.x series.
> Update for theming.md so it's correct.

- administration/getting_started.md
Added some more explicit information about java needs since it's been coming up more frequently lately. Anything can be improved, but one specific area might be instructions or a link for how to force your machine to use a certain java version for ArchivesSpace.
> Updates to java language

- provisioning/domains.md
adds in missing ngnix config file
> add nginx config

- administration/windows.md
had an extra ( there than made the procrun link fail.
> fix  broken link

- administration/getting_started.md
as of 2.6 Java 7 no longer works.
> Java 8 required

- development/reports.md
Use parens instead of brackets for row.delete method
> Report.delete method - use parens

- customization/configuration.md
Small changes to make a couple PUI config settings less confusing.
> Small PUI config changes

- development/docker.md
Clarify purpose of Docker config included with ArchivesSpace. Pairs with: https://github.com/archivesspace/archivesspace/pull/1670
> Docker disclaimer

- provisioning/clustering.md
- provisioning/mysql.md
Maven now requires https so changed in the examples
> Maven now requiring https and changed from central repo to repo1 for security certificate

- customization/configuration.md
- customization/customizing_PUI_examples/config.rb
I have updated what was existing with new information for release v2.8.0. Still need to update the configuration list with more parameters but thought it was important to add new ones for this release, specifically.
> Modify configuration parameters for v2.8.0

- development/build.md
Add a noted about which ports it runs on with supervisord
> note for which ports

- customization/plugins.md
Expanded the note about overriding core modules/controllers to provide info on how to do it + an example.
> added info/example on overriding core modules/controllers

- customization/plugins.md
Update plugin documentation to include frontend specific hooks available for plugin development.
In support of changes in:
> https://github.com/archivesspace/archivesspace/pull/1896
> Plugin documentation changes from Queensland State Archives development

- development/release.md
A few additional small changes to the release build process, as well as fixing list numbering by indenting code blocks.
> Small additions/style changes to release steps

- architecture/README.md
two small edits to remove a closing parenthesis and fix a broken link - that's it!
> super small edit to fix typos

- administration/upgrading.md
Add a note about reindexing being required sometimes.
> Indexes note

- development/release.md
@trevorthornton These should (hopefully) be the final changes to this for a while.  This complements recent changes to the release notes build task (makes things less manual for us in the future), and can be reviewed/merged whenever you'd like.  Thanks!
> Additional tweaks to building a release documentation

- development/release.md
Use an environment variable to set the yard footer version value rather than hardcoded value in `asconstants.rb`
See https://github.com/archivesspace/archivesspace/pull/2134
> edit yard doc instructions

- migrations/migration_tools.md
Additional maps, including MARCXML authority and EAC-CPF, which are new for v3.0.0.
> Additional data maps

- development/dev.md
Adding some very basic guidance about submitting a PR (mostly copied from the old/outdated Developer Onboarding documentation in the wiki).
> Copy over some info on submitting PRs from the old dev onboarding docs

- migrations/migration_tools.md
These changes come out of the Metadata Standards sub-team's work.
> Updates to MARCXML maps

- customization/theming.md
Noticed this teeny thing when the pr notification for this helpful edit showed up in my email.
> typo patrol

- provisioning/solr.md
It was really easy to over look what version is supported so I'm just calling that out.
> Put some emphasis on that solr version location

- administration/security.md
- readme_implement.md
Not even close to being ready, but I wanted to see what everyone thinks about these as topic areas. Too much? Not enough? What's missing?
> Security Considerations - Review draft for ideas

- development/release.md
a few small fixes to the release process docs
> minor updates to release documentation

- administration/getting_started.md
[ANW-2028]
[ANW-2028]: https://archivesspace.atlassian.net/browse/ANW-2028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> document the NodeJS requirement

- provisioning/solr.md
Pointing the link to the latest 8.x release
> Update link to solr docs

- customization/authentication.md
> fixing the oauth plugin link

- architecture/oai-pmh/README.md
see also: https://github.com/archivesspace/archivesspace/pull/3271
> update oai identifiers doc

- src/content/docs/administration/docker.md
- src/content/docs/development/docker.md
- src/siteNavigation.json
[ANW-2218 ]
https://github.com/archivesspace/archivesspace/pull/3420
As discussed with @brianzelip this PR contains only the content changes related to supporting Docker and no structure changes. 
Do not merge before: https://github.com/archivesspace/archivesspace/pull/3420 gets merged
> ANW-2218 docker related content

- src/content/docs/provisioning/solr.md
see also: https://github.com/archivesspace/archivesspace/pull/3453
> ANW-2220 do not require an env variable to enable analysis-extras

- cypress/e2e/content-pages.cy.js
- cypress/e2e/sitemap.cy.js
This PR makes minor changes to two e2e tests.
> Tweak content pages and sitemap tests

- src/content/docs/administration/docker.md
- src/content/docs/administration/upgrading.md
Add detailed upgrading instructions for users of the Docker configuration package, including steps for handling solr configuration/schema changes. Update the upgrading guide for the zip distribution to reference Docker-specific instructions and clarify the distinction between the two installation methods.
> ANW-2383 update upgrading instructions for Docker and zip distribution

- src/content/docs/customization/locales.md
- src/content/docs/customization/plugins.md
- src/content/docs/customization/reports.md
- src/content/docs/customization/theming.md
- src/content/docs/customization/xsl.md
- src/content/docs/development/dev.md
- src/content/docs/development/docker.md
- src/content/docs/development/ead-exporter.md
- src/content/docs/development/index.md
- src/content/docs/development/jruby-rack-build.md
- src/content/docs/development/release.md
- src/content/docs/development/release_schema_versions.md
- src/content/docs/development/releases.md
- src/content/docs/development/ui_test.md
- src/content/docs/development/vscode.md
- src/content/docs/migrations/migrate_from_archivists_toolkit.md
- src/content/docs/migrations/migrate_from_archon.md
- src/content/docs/migrations/migration_tools.md
- src/content/docs/provisioning/clustering.md
- src/content/docs/provisioning/domains.md
- src/content/docs/provisioning/https.md
- src/content/docs/provisioning/index.md
- src/content/docs/provisioning/jmeter.md
- src/content/docs/provisioning/mysql.md
- src/content/docs/provisioning/newrelic.md
- src/content/docs/provisioning/prefix.md
- src/content/docs/provisioning/robots.md
- src/content/docs/provisioning/solr.md
- src/content/docs/provisioning/tuning.md
Added descriptions for 29 markdown files.
> Mpaqu lib patch 1

- src/content/docs/administration/indexes.md
There's this for powershell that   works for Windows. Hopefully this formatting works
> Update indexes.md to show powershell command
