_yard/Gemfile, _yard/Gemfile.lock
in the server in YARD before 0.9.11 does not block relative paths with an initial ../ sequence, which allows attackers to conduct directory traversal attacks and read arbitrary files.
=> Update yard gem because of CVE-2017-17042 lib/yard/core_ext/file.rb 

customization/README.md
I believe the outline should be re-ordered with "ease of use" for a new user in mind.
Even though customizing text involves the plugins/local/ subdirectory, understanding plugins in general is *not* necessary to accomplish this goal.
=> re-order outline

customization/plugins.md
The important point of the "overriding locales" section is that not every subdirectory needs to be defined in a given plugin.  I've re-arranged the info there (and renamed it), including a link to the Customizing Text README.  I've also re-written the beginning paragraph.
=> Re-organized some of the information

customization/authentication.md
can be added as a plug-in to ArchivesSpace. Fixes https://github.com/archivesspace/tech-docs/issues/2.
=> Update authentication documentation to describe how local authentication

administration/upgrading/UPGRADING_1.5.0.md, administration/upgrading/UPGRADING_2.1.0.md, development/docker.md, development/supervisord.md, migrations/migrate_from_archivists_toolkit.md, provisioning/clustering.md
In order to create the technical documentation static HTML pages, needed to remove "smart" single quotes from migrations/migrate_from_archivists_toolkit.md.
Also, in the other files, needed to change the way hash tags (#) are in the files to ensure that appropriate sub static pages are created.
=> Fix special chars

development/public_test.md
Adds a readme for the existing tests for the PUI.  This duplicates the readme in core that was added via: https://github.com/archivesspace/archivesspace/pull/1391
=> Add readme for public tests

customization/configuration.md
Three OAI-PMH settings have been moved out of the config file to make them easier for the folks managing repositories to set them. They will be kept in the config file with a note stating deprecated for 2.5.2 but will be removed from the config file in 2.6.0. Hopefully, that will make the change more obvious when upgrading. Please improve the wording of the note if it is not clear.
=> Documenting deprecated OAI-PMH settings for release 2.5.2

administration/backup.md
Solr backups are defaulted to happen at midnight
=> Make sure documentation matches actual values

development/build.md, development/release.md
A few changes to improve documentation on building/testing just the API docs (Slate).  Also, indicating that middleman doesn't like bundler 2+.  Finally, fixing a few typos.
=> Clarify building API docs only, indicate necesary bundler version, typos

customization/theming.md
Throw in an example of how to make the PUI header logo have a link
=> logo-link-example

administration/indexes.md, api/README.md, development/release.md, development/ui_test.md
Added a few more items to Post-Release steps in `development/release.md`.
Also found/removed all instances of lines beginning with single #'s inside of codeblocks, such as:
````
```
```
````
as these cause the docs build process to abruptly end a page at the # and begin a new stub of a docs page following the #.
=> Cleanup comments and add some post-release steps

api/README.md
Just a small change to the API docs to encourage people to not allow public access to the API endpoint.
=> Add note to API about firewall

development/release.md
This may still be a bit of a work in progress, but is a huge step in the right direction of documenting how the release process will look from v2.8.1 onward now that we won't be building the tech docs as part of the release.
=> Update release process documentation

customization/theming.md
Upstream changes in Rails now means that alt text needs to be explicitly set when using `image_tag`.  This means our guidance on theming via plugins (and, for the PUI, via `AppConfig`) should encourage users to provide alt text.
Note: This functionality won't be in place until the v2.8.1 release which should include https://github.com/archivesspace/archivesspace/pull/2019, so I'm PRing this as a draft until that release is out.
=> Update theming to compliment PR#2019

development/dev.md
Adds a section about Rubocop, which is now part of the CI checks applied to pull requests.
=> add rubocop task to development notes

customization/configuration.md
This PR adds `AppConfig[:pui_expand_all]` to the configuration docs as a result of [ArchivesSpace PR 2538](https://github.com/archivesspace/archivesspace/pull/2538).
=> ANW-730 Add PUI expand all option to configuration

administration/getting_started.md
Looks like an incorrect path was introduced on this one, though it's correct further down in the document.
=> Fixing broken link for external solr

administration/unix_daemon.md
Updates example of a systemd file for ArchivesSpace.
`Type=forking` doesn't work with AS because it doesn't detach and background itself. I've changed it to `Type=simple` because it's a long running process that doesn't automatically detach itself from the shell.
Additionally, the `ExecStart` and `ExecStop` lines don't need the `start` and `stop` commands.
=> Update unix daemon example

development/release.md
Updates to the release document to better describe typical release tag workflow and the [updated workflow for publishing API documentation](https://github.com/archivesspace/archivesspace/pull/2660)
=> update release doc to reflect simpler API document generation workflow

provisioning/https.md
Added some text to inform users about web server options for setting the SameSite cookie attribute. 
https://archivesspace.atlassian.net/browse/ANW-1086
=> ANW-1086: information to address SameSite cookie attribute warnings

development/dev.md
The "**./**" is present in other locations where the "build/..." commands is referenced but on this page it's missing. As a new person to the project I found this to be a bit of a "_trip hazard_" when trying to blindly follow the instructions.
=> Small correction with commands

development/README.md, development/vscode.md, readme_develop.md
This PR adds documentation for using VS Code as a local development editor, and updates relevant navigation lists with links to the new docs.
Closes #149
=> GH-149: Document using VS Code for local development

customization/plugins.md
Fixes a broken link as identified in this issue comment: https://github.com/archivesspace/tech-docs/issues/156#issuecomment-1568949723
=> Fix broken link to Hello World plugin readme

development/release.md
afterwards a second PR merges the changes from the release branch to master
=> avoid cherry picking and merge hotfixes to the release branch instead.

provisioning/solr.md
This link was to mast and if someone uses those versions they're going to have a bad time unless they're lucky enough to have that same version of ArchivesSpace running. No need to link to them here it's just confusing.
=> Drop confusing link to master version of configs

src/content/docs/customization/plugins.md
This PR adds docs on customizing the public and frontend favicons, with plugin examples for each application.
=> TD-19 Add favicon customization docs

astro.config.mjs
This PR updates the "edit this page on GitHub" link url in the Astro config since the new site has now been merged into master.
The production branch in the Cloudflare settings have also been updated accordingly, so Cloudflare will start building from master once this PR gets merged.
After this PR is merged and Cloudflare is confirmed to be working as expected, the `astro-starlight` branch can be deleted.
[TD-17](https://archivesspace.atlassian.net/browse/TD-17)
[TD-17]: https://archivesspace.atlassian.net/browse/TD-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-17 Update branch name in github editLink url

src/content/docs/about/development.md
This PR adds a note to the about development docs that explains why the Node.js version in .nvmrc is what it is.
=> Add about dev note explaining the Node.js version in .nvmrc

astro.config.mjs
This PR updates the codebase to reflect the default branch change to `main` that occurred on 2025-01-21.
In addition to the Astro config file changed herein, branch info was updated in this repo's GitHub and Cloudflare settings.
[TD-29](https://archivesspace.atlassian.net/browse/TD-29)
[TD-29]: https://archivesspace.atlassian.net/browse/TD-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-29 Change default branch to main

README.md
This PR updates the root README to reflect the new site.
=> TD-30: Update readme to reflect the new site

astro.config.mjs, cypress/e2e/release-badge.cy.js, src/components/ReleaseBadge.astro, src/components/overrides/Header.astro, src/components/overrides/MobileMenuFooter.astro, src/utils/gitMetadata.mjs
This PR adds a dynamic 'latest release badge' to the desktop and the mobile menu footer. It fetches, displays, and links to the latest release tag on page load in the format commonly found on README.md files throughout GitHub, etc.
The 2 commits are intended to be separate for provenance.
[TD-31](https://archivesspace.atlassian.net/browse/TD-31)
[TD-31]: https://archivesspace.atlassian.net/browse/TD-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-31: Add release badge for the latest ArchivesSpace release

cypress/e2e/release-badge.cy.js, src/components/ReleaseBadge.astro
Just changes the blue color on the recently added release badge to the dark blue from the ArchivesSpace logo.
=> Change release badge blue color

src/content/docs/administration/docker.md
[ANW-2218] see also: https://github.com/archivesspace/archivesspace/pull/3420
[ANW-2218]: https://archivesspace.atlassian.net/browse/ANW-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2218 update docker docs

src/content/docs/provisioning/solr.md
[ANW-2263] see also: https://github.com/archivesspace/archivesspace/pull/3467
[ANW-2263]: https://archivesspace.atlassian.net/browse/ANW-2263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2263 env variable to enable analysis extras solr module

astro.config.mjs, package-lock.json, package.json, src/components/IssueLink.astro, src/components/overrides/EditLink.astro, src/components/overrides/Footer.astro, src/components/overrides/Header.astro, src/components/overrides/MobileMenuFooter.astro, src/components/overrides/Sidebar.astro, src/components/overrides/SocialIcons.astro
This PR updates dependencies and syncs the codebase with recent breaking changes to the underlying Starlight framework:
- [v0.32.0](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.32.0) changed the data object for the current route from `Astro.props` to `Astro.locals.starlightRoute`
- [v0.33.0](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.33.0) changed the `social` configuration option data structure
Starlight non-breaking changes included adding [`@layer`](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) scopes to core component style blocks.
=> ANW-2378 Update dependencies and rectify Starlight breaking changes
